Add new providers
movie-web/providers pull request #10
Opened 2023-09-28 03:51 UTC by zisra

This pull request addresses the following issues:
- Adds flixhq show support [#437](https://github.com/movie-web/movie-web/issues/437)
- Stringifies CLI results so nested objects are shown

 - [x] I have read and agreed to the [code of conduct](https://github.com/movie-web/movie-web/blob/dev/.github/CODE_OF_CONDUCT.md).
 - [ ] I have read and complied with the [contributing guidelines](https://github.com/movie-web/movie-web/blob/dev/.github/CONTRIBUTING.md).
 - [ ] What I'm implementing was assigned to me and is an [approved issue](https://github.com/movie-web/movie-web/issues?q=is%3Aopen+is%3Aissue+label%3Aapproved). For reference, please take a look at our [GitHub projects](https://github.com/movie-web/movie-web/projects).
 - [ ] I have tested all of my changes.

2023-09-28 12:55 UTC, mrjvs commented on src/dev-cli.ts
>      } catch (error) {
I would prefer a util.inspect instead of a stringify, looks a bit prettier.

```
const util = require('util')

console.log(util.inspect(myObject, {showHidden: false, depth: null, colors: true}))
```

2023-09-28 12:55 UTC, mrjvs commented on src/utils/compare.ts
>  }
this check already exists. if releaseYear is undefined. it wont compare the year.

2023-10-03 21:33 UTC, mrjvs requested changes
On top of the review comments, make sure you resolve merge conflicts.

in the merge, mind the fact that nanoid has been reintroduced, don't revert that change.

2023-10-03 21:33 UTC, mrjvs commented on src/dev-cli.ts
> +
rename to `logDeepObject`, change input type to `Record<any, any>` and actually use the function at the places where it needs to log the result.

2023-10-03 21:33 UTC, mrjvs commented on src/providers/embeds/febBox.ts
> +    });
use proxied fetcher for all requests that dont have CORS headers set right

2023-10-03 21:33 UTC, mrjvs commented on src/providers/sources/flixhq/scrape.ts
> +  }
make a new function for getting show sources instead of merging show and movie. the two types have no shared fucntionality

2023-10-03 22:04 UTC, mrjvs requested changes

2023-10-03 22:04 UTC, mrjvs commented on src/dev-cli.ts
>      } catch (error) {
dont console.log a console.log return value. thats a double log.

2023-10-03 22:34 UTC, mrjvs commented
please resolve the merge conflicts

2023-10-07 01:19 UTC, zisra commented
Sorry for the confusion, but I think it would be best to drop Febbox. Superstream has two types of different stream/url resolvers, one of them is for newer high quality movies and the other is for low quality movies. We already implement the 1080p one. I have found an endpoint that is way simpler to use and works well with both shows and movies, could I replace it with febbox? It responds with the same exact links.

2023-10-26 19:09 UTC, mrjvs approved these changes

2023-10-26 19:15 UTC, mrjvs commented
I've checked the code, all looks in order. Ive pushed a fix for native fetch not working for febbox.
also added some bugfixes for unrelated things.
It's ready for merge, gonna make a patch release out of it as well.

> Sorry for the confusion, but I think it would be best to drop Febbox. Superstream has two types of different stream/url resolvers, one of them is for newer high quality movies and the other is for low quality movies. We already implement the 1080p one. I have found an endpoint that is way simpler to use and works well with both high quality shows and movies, could I replace it with febbox? It responds with the same exact links.

It depends on how stable that endpoint is, if you can make an issue for it and give more details on the endpoint we can look at it together. But for now we're going with the current state of the PR.

2023-10-26 19:15 UTC, merged