Updated compare function to check a edge case
movie-web/providers pull request #105
Opened 2024-03-04 22:19 UTC by capak07

This pull request resolves #227
- Updated the normalizeTitle function to cover an edge case where the title contains the "The Movie"

 - [ ] I have read and agreed to the [code of conduct](https://github.com/movie-web/movie-web/blob/dev/.github/CODE_OF_CONDUCT.md).
 - [ ] I have read and complied with the [contributing guidelines](https://github.com/movie-web/movie-web/blob/dev/.github/CONTRIBUTING.md).
 - [ ] What I'm implementing was assigned to me and is an [approved issue](https://github.com/movie-web/movie-web/issues?q=is%3Aopen+is%3Aissue+label%3Aapproved). For reference, please take a look at our [GitHub projects](https://github.com/movie-web/movie-web/projects).
 - [ ] I have tested all of my changes.

2024-03-04 22:22 UTC, binaryoverload requested changes

2024-03-04 22:22 UTC, binaryoverload commented on src/utils/compare.ts
> +  return titleTrimmed
I would move the toLowerCase to before this check and then do the "the movie" check in lowercase to avoid any weird capitalisation

2024-03-04 22:24 UTC, zisra commented
Also add "the series"

2024-03-07 16:11 UTC, binaryoverload requested changes

2024-03-14 20:31 UTC, binaryoverload approved these changes

2024-03-14 20:48 UTC, JorrinKievit approved these changes

2024-03-14 20:52 UTC, merged