Primewire
movie-web/providers pull request #116
Opened 2024-03-15 04:29 UTC by zisra

Primewire

2024-03-27 22:28 UTC, JorrinKievit commented on src/providers/sources/primewire/blowfish.ts
> +const pArray = [
Can we move these arrays to its own file?

2024-03-27 22:28 UTC, JorrinKievit commented on src/providers/sources/primewire/blowfish.ts
Could we have a short description on what this file is, how to maintain, etc?

2024-03-27 22:28 UTC, JorrinKievit commented on src/providers/sources/primewire/blowfish.ts
> +  bd(e: string) {
Rename this function to something descriptive

2024-03-27 22:28 UTC, JorrinKievit commented on src/providers/sources/primewire/index.ts
> +    if (link.includes(link)) {
This always resolves to true?

2024-03-27 22:28 UTC, JorrinKievit commented on src/providers/sources/primewire/index.ts
> +        url: `https://www.primewire.tf/links/go/${links[link]}`,
can use the baseUrl here

2024-03-27 22:28 UTC, JorrinKievit commented on src/providers/sources/primewire/blowfish.ts
> +export function getLinks(e: string) {
What is e?

2024-03-27 22:28 UTC, JorrinKievit commented on src/providers/sources/primewire/blowfish.ts
> +  const t = e.slice(-10);
Same for these, a descriptive variable name if possible

2024-03-28 02:29 UTC, zisra commented on src/providers/sources/primewire/index.ts
> +    if (link.includes(link)) {
https://eslint.org/docs/latest/rules/guard-for-in

2024-03-28 17:45 UTC, JorrinKievit requested changes
Few remarks:

- Upstream returns a 403 for the HLS playlist. Probably needs a referer so should be used extension only (IP_LOCKED flag)?
- The streams are not that fast, are mostly 720p and have no subtitles. So for that reason I would rank it below VidSrcTo (I'm gonna rerank for the new release anyway but just for this PR's sake)
- Could be worth investigating if its faster on primewire's site itself, and we can add headers to the streams for faster load speeds?

2024-03-28 17:45 UTC, JorrinKievit commented on src/providers/sources/primewire/index.ts
> +    const title = await ctx.fetcher<string>(`movie/${searchResult}`, {
This should be proxied

2024-03-28 17:45 UTC, JorrinKievit commented on src/providers/sources/primewire/index.ts
> +    const season = await ctx.fetcher<string>(`tv/${searchResult}`, {
This too

2024-03-28 22:35 UTC, JorrinKievit approved these changes

2024-03-28 22:35 UTC, merged