Add ZoeChip source & mixdrop and upstream embeds
movie-web/providers pull request #12
Opened 2023-09-28 22:24 UTC by jonbarrow

- [x] I have read and agreed to the [code of conduct](https://github.com/movie-web/movie-web/blob/dev/.github/CODE_OF_CONDUCT.md).
 - [x] I have read and complied with the [contributing guidelines](https://github.com/movie-web/movie-web/blob/dev/.github/CONTRIBUTING.md).
 - [ ] What I'm implementing was assigned to me and is an [approved issue](https://github.com/movie-web/movie-web/issues?q=is%3Aopen+is%3Aissue+label%3Aapproved). For reference, please take a look at our [GitHub projects](https://github.com/movie-web/movie-web/projects).
 - [x] I have tested all of my changes.

## Changes

- Added https://zoechip.cc/ source provider, both movies and TV shows
- Added https://mixdrop.co/ and https://upstream.to/ embed providers
- Added an optional `headers` property to `StreamFile`. This is required for mixdrop streams

## Notes

- Mixdrop returns mp4 file streams, but the only way to pass these is by using `qualities`. Mixdrop does not provide stream quality information, so this just defaults to 1080. I would propose that something like an `unknown` option also be added for `qualities` for these cases
- Not related to this PR, but something I noticed while working on it. `SourcererOutput` only currently allows for multiple embeds to be returned, but not multiple streams. There are cases where this is insufficient. I have written multiple scrapers in the past which return more than one raw streams, not embeds, but given the current system only one of them would be allowed

2023-09-28 22:35 UTC, mrjvs reviewed
Just some initial thoughts in the review comments. I'll take a proper look tomorrow evening (going to bed now).

Also speedy work, nicely done

2023-09-28 22:35 UTC, mrjvs commented on src/providers/streams.ts
>  export type Qualities = '360' | '480' | '720' | '1080';
You can add unknown to this union for mixdrop.

2023-09-28 22:35 UTC, mrjvs commented on src/providers/embeds/mixdrop.ts
> +            flags: [flags.NO_CORS],
While the stream may not have restricted cors headers. Due to needing the referer header to be set, it is still not possible to use cross origin. Maybe this flag should be removed or mayhaps we rename the flag to more accurately represent browser restrictions.

I'm unsure, what's your view?

2023-09-28 22:41 UTC, jonbarrow commented on src/providers/embeds/mixdrop.ts
> +            flags: [flags.NO_CORS],
Either renaming the flag or having more clear documentation about when to use the flag(s) would be my suggestion. I know the library is still in it's infancy, so I understand there not being very robust documentation atm. That being said, there are definitely some things that remain unclear without having to dig through source, such as the flags, the context system, the `rank` system, etc

2023-09-28 22:42 UTC, jonbarrow commented on src/providers/streams.ts
>  export type Qualities = '360' | '480' | '720' | '1080';
Sounds good :+1:

2023-09-29 18:18 UTC, mrjvs requested changes
Looked through it and it looks great.
just a few changes to accommodate my happy path addiction.

I will keep the multi-stream output for sources in mind, ill work that in sometime soon:tm:

2023-09-29 18:18 UTC, mrjvs commented on src/providers/sources/zoechip/scrape.ts
> +  }
I would prefer a happy path here.

```ts
const foundSeason = seasons.find(season => season.season === media.season.number)
if (!foundSeason) return null;
return foundSeason.id;
```

2023-09-29 18:18 UTC, mrjvs commented on src/providers/sources/zoechip/scrape.ts
> +  }
same thing for `getZoeChipEpisodeID` with the episodes

2023-09-29 18:18 UTC, mrjvs commented on src/providers/sources/zoechip/search.ts
> +      }
maybe use compareMedia() here again, but with the new year passed in.
that way if we ever change the comparison logic, we wouldn't miss zoechip's.

2023-09-29 18:18 UTC, mrjvs commented on src/providers/embeds/mixdrop.ts
> +        const url = link[1];
instead of nested ifs. I would prefer happy path here.

```ts
if (!packed) throw new Error("");
...

if (!link) throw new Error("");
...

return {};
```

another benefit of this approach is more specific exit cases in the error message. Can be useful in logs to see where a problem lies.

2023-09-29 18:23 UTC, jonbarrow commented on src/providers/sources/zoechip/scrape.ts
> +  }
Is this commenting on `for` vs `find`, the use of multi-line `if`, or both?

For instance, would either of these also be acceptable?

```ts
const foundSeason = seasons.find(season => season.season === media.season.number);
if (!foundSeason) {
	return null;
}
return foundSeason.id;
```

```ts
const foundSeason = seasons.find(season => season.season === media.season.number);
return foundSeason?.id;
```

Just trying to nail down what the style for the library is to keep it consistent

2023-09-29 18:32 UTC, mrjvs commented on src/providers/sources/zoechip/scrape.ts
> +  }
im commenting more specifically on the happy path, where the final results is almost always kept end of the function, early returns are seen as exit conditions and the most "happy" result is last return statement, which in this case would the season ID.

I dont mind the use of `for` vs `find`. just the fact that the happiest result is the last return.

---
if I had to give a preference, it would be the code snippet below, but I find any acceptable as long as its happy path.
```ts
const foundSeason = seasons.find(season => season.season === media.season.number);
if (!foundSeason) {
	return null;
}
return foundSeason.id;
```

I appreciate the effort in keeping inline with the code style, not many people do that. thanks :smile:

2023-09-29 18:35 UTC, jonbarrow commented on src/providers/sources/zoechip/scrape.ts
> +  }
Sounds good!

> I appreciate the effort in keeping inline with the code style, not many people do that. thanks 😄

Ever since starting to do Pretendo full time, I've come to know the pain of people trying to contribute meaningless changes or changes which break the existing code style lol. So I've definitely become a lot more cautious about it

2023-09-29 18:48 UTC, mrjvs commented
speedy boi, gonna run a few tests and then merge.

2023-09-29 18:56 UTC, mrjvs commented on src/providers/sources/zoechip/scrape.ts
> +  return details.link;
just to make sure, these are "sometime in the future" todos and not for this PR. right?

2023-09-29 19:01 UTC, mrjvs commented on src/providers/sources/zoechip/scrape.ts
> +  return details.link;
:+1:

2023-09-29 19:01 UTC, mrjvs approved these changes

2023-09-29 19:01 UTC, merged

2023-09-29 19:02 UTC, mrjvs commented
tests went through without any issues. using your interactive cli tester of course.
thanks for the work :)