Add Insertunit provider
movie-web/providers pull request #146
Opened 2024-04-07 09:08 UTC by infvortx

This pull request resolves a Discord request (not an issue), adds Insertunit, it is a Russian-based provider that has the original English tracks.

Streams aren't locked in any way.

 - [X] I have read and agreed to the [code of conduct](https://github.com/movie-web/movie-web/blob/dev/.github/CODE_OF_CONDUCT.md).
 - [X] I have read and complied with the [contributing guidelines](https://github.com/movie-web/movie-web/blob/dev/.github/CONTRIBUTING.md).
 - [ ] What I'm implementing was assigned to me and is an [approved issue](https://github.com/movie-web/movie-web/issues?q=is%3Aopen+is%3Aissue+label%3Aapproved). For reference, please take a look at our [GitHub projects](https://github.com/movie-web/movie-web/projects).
 - [X] I have tested all of my changes.

2024-04-09 06:49 UTC, infvortx commented
Added subtitles and types. 

I was not able to figure out the returning of a thumbnail track as I was not able to find any thumbnail tracks in the player.

2024-04-09 18:55 UTC, JorrinKievit requested changes

2024-04-09 18:55 UTC, JorrinKievit commented on src/providers/sources/insertunit/types.ts
> +        names: [];
```suggestion
        names: string[];
```

2024-04-09 18:55 UTC, JorrinKievit commented on src/providers/sources/insertunit/types.ts
> +        order: [];
```suggestion
        order: number[];
```

2024-04-09 18:55 UTC, JorrinKievit commented on src/providers/sources/insertunit/types.ts
> +    cc: []
```suggestion
    cc: string[]
```

2024-04-09 18:55 UTC, JorrinKievit commented on src/providers/sources/insertunit/types.ts
> +    sections: []
```suggestion
    sections: string[]
```

2024-04-09 18:55 UTC, JorrinKievit commented on src/providers/sources/insertunit/types.ts
> +        src: string;
Isnt this the thumbnail url?

2024-04-09 18:55 UTC, JorrinKievit commented on src/providers/sources/insertunit/insertunit.ts
> +      for (subtitle of subtitleData as Subtitle[]) {
```suggestion
      for (const subtitle of subtitleData as Subtitle[]) {
```

2024-04-09 18:55 UTC, JorrinKievit commented on src/providers/sources/insertunit/insertunit.ts
> +      let subtitle: Subtitle;
```suggestion
```

2024-04-09 18:55 UTC, JorrinKievit commented on src/providers/sources/insertunit/insertunit.ts
> +      for (subtitle of subtitleData as Subtitle[]) {
Can we extract getting the captions to a function, since its the same for both scraping the movie and the tv show?

2024-04-09 19:30 UTC, jevinruv commented
Not all videos return english audio in the video?

2024-04-10 01:42 UTC, infvortx commented on src/providers/sources/insertunit/types.ts
> +        src: string;
It is, but it isn't a VTT track, I was not able to find a way to return it.

This is what you'd get:

https://img.zcvh.net/693392/desktop/thumb-1.webp

2024-04-10 04:26 UTC, infvortx commented on src/providers/sources/insertunit/types.ts
> +    cc: []
Did Subtitle[] here instead as we already have a subtitle type.

2024-04-10 20:51 UTC, JorrinKievit requested changes

2024-04-10 20:51 UTC, JorrinKievit commented on src/providers/sources/insertunit/captions.ts
> +    for (subtitle of data) {
```suggestion
    for (const subtitle of data) {
```

2024-04-10 20:51 UTC, JorrinKievit commented on src/providers/sources/insertunit/captions.ts
> +    let subtitle: Subtitle;
```suggestion
```

2024-04-10 20:51 UTC, JorrinKievit commented on src/providers/sources/insertunit/insertunit.ts
> +    if (currentEpisode.cc != null) {
?

2024-04-11 00:53 UTC, infvortx commented on src/providers/sources/insertunit/insertunit.ts
> +    if (currentEpisode.cc != null) {
Was a left over I didn't notice, my bad.

2024-04-11 13:48 UTC, JorrinKievit approved these changes

2024-04-11 13:50 UTC, JorrinKievit commented
@infvortx fyi pipeline is failing because of prettier format errors

2024-04-11 14:53 UTC, infvortx commented
Prettier errors should be fixed now.

2024-04-11 17:46 UTC, JorrinKievit approved these changes

2024-04-11 17:46 UTC, merged