Add lookmovie
movie-web/providers pull request #15
Opened 2023-10-01 20:09 UTC by JipFr

This pull request resolves #XXX

 - [x] I have read and agreed to the [code of conduct](https://github.com/movie-web/movie-web/blob/dev/.github/CODE_OF_CONDUCT.md).
 - [x] I have read and complied with the [contributing guidelines](https://github.com/movie-web/movie-web/blob/dev/.github/CONTRIBUTING.md).
 - [ ] What I'm implementing was assigned to me and is an [approved issue](https://github.com/movie-web/movie-web/issues?q=is%3Aopen+is%3Aissue+label%3Aapproved). For reference, please take a look at our [GitHub projects](https://github.com/movie-web/movie-web/projects).
 - [x] I have tested all of my changes.

2023-10-03 17:35 UTC, binaryoverload commented on src/providers/sources/lookmovie/video.ts
> +    url = `https://www.lookmovie2.to/api/v1/security/movie-access?id_movie=${config.id_movie}&hash=${config.hash}&expires=${config.expires}`;
I assume the inconsistencies between `id_movie` and `episodeId` are LokLok's thing?

Also it seems that when the config option is passed in (https://github.com/movie-web/providers/pull/15/files#diff-20980de874adb0244ef7ce68a1e8e3b464304a20881a0183a425609b508ae7a0R58) it's using `movieId` not `id_movie`?

2023-10-03 21:42 UTC, mrjvs requested changes

2023-10-03 21:42 UTC, mrjvs commented on src/providers/sources/lookmovie/util.ts
> +  ).then((d) => d.json());
use the fetcher on the context. the fetcher can also handle querty params and base urls.
(dont use the proxied fetcher, as the streams are ip based)

2023-10-03 21:42 UTC, mrjvs commented on src/providers/sources/lookmovie/util.ts
> +  ).then((d) => d.json());
and it auto parses json

2023-10-03 21:42 UTC, mrjvs commented on src/providers/sources/lookmovie/util.ts
> +  ).then((d) => d.json());
(this applies to everywhere where fetch is used, ill only comment it once here)

2023-10-03 21:42 UTC, mrjvs commented on src/providers/sources/lookmovie/video.ts
> +  const opts = ['1080p', '1080', '720p', '720', '480p', '480', 'auto'];
I would prioritize auto, as I assume its a HLS stream of all qualities, just that the client can automatically select which one gets chosen.

2023-10-03 21:42 UTC, mrjvs commented on src/providers/sources/lookmovie/index.ts
> +export const lookmovieScraper = makeSourcerer({
make a new flag `IP_BASED`. which will mean that the streams are based on the ip it gets requested from.
then add the flag to both the streams and source itself

2023-11-08 16:32 UTC, MemeCornucopia commented
This would be a really good addition

2023-11-08 16:33 UTC, JipFr commented
If it worked, sure. But it doesn't. They've re-added the captcha, so this provider will never work. I'm closing the PR until that might change, in which case we can re-open it.

2023-11-08 16:33 UTC, closed without merging

2023-11-21 23:56 UTC, MemeCornucopia commented
Well actually I did a little digging, I downloaded their mobile app which is for "premium" users only, but I did a little trolling and intercepted the requests from the server and told the client I had premium I then found out that they have no captchas / protection for their mobile api thus making this actually possible

2023-11-21 23:57 UTC, MemeCornucopia commented
![image](https://github.com/movie-web/providers/assets/148788549/4dddf836-7c20-4e7c-9c1a-2cf17da6965b)
![image](https://github.com/movie-web/providers/assets/148788549/0e42a97b-eef2-451c-a02a-644b9997271d)

https://lmscript.xyz/v1/movies/view?expand=streams&id=110465

2023-11-22 00:03 UTC, mrjvs commented
From the looks of it, it looks possible. No accounts, no cors protection, no captchas.

Who wants to pick this up?