add WarezCDN
movie-web/providers pull request #151
Opened 2024-04-11 11:30 UTC by lonelil

This pull request resolves #XXX

 - [x] I have read and agreed to the [code of conduct](https://github.com/movie-web/movie-web/blob/dev/.github/CODE_OF_CONDUCT.md).
 - [x] I have read and complied with the [contributing guidelines](https://github.com/movie-web/movie-web/blob/dev/.github/CONTRIBUTING.md).
 - [x] What I'm implementing was assigned to me and is an [approved issue](https://github.com/movie-web/movie-web/issues?q=is%3Aopen+is%3Aissue+label%3Aapproved). For reference, please take a look at our [GitHub projects](https://github.com/movie-web/movie-web/projects).
 - [x] I have tested all of my changes.

2024-04-11 13:56 UTC, JorrinKievit requested changes

2024-04-11 13:56 UTC, JorrinKievit commented on src/providers/sources/warezcdn/index.ts
> +      const realUrl = await ctx.proxiedFetcher<string>(`/getPlay.php?${params}`, {
Imo more constistent to use query object here, so 
```
{
  baseUrl: warezcdnApiBase,
  query: {
      id: embedUrl,
     sv: 'mixdrop'
}
```

2024-04-11 13:56 UTC, JorrinKievit commented on src/providers/sources/warezcdn/index.ts
> +  } as SourcererOutput;
Hmm why is the type assertion needed 🤔

2024-04-11 13:56 UTC, JorrinKievit commented on src/providers/embeds/warezcdn/common.ts
> +export const warezcdnWorkerProxy = 'https://workerproxy.warezcdn.workers.dev';
can this be moved to the common.ts file with the other constants

2024-04-11 13:56 UTC, JorrinKievit commented on src/providers/embeds/warezcdn/common.ts
> +  const page = await ctx.proxiedFetcher<string>(`/player.php?${new URLSearchParams({ id: ctx.url })}`, {
Same here with the query object

2024-04-11 14:02 UTC, lonelil commented on src/providers/sources/warezcdn/index.ts
> +      const realUrl = await ctx.proxiedFetcher<string>(`/getPlay.php?${params}`, {
omg i forgot the query option existed

2024-04-11 14:06 UTC, lonelil commented on src/providers/sources/warezcdn/index.ts
> +  } as SourcererOutput;
was copying from my own project, forgot to remove

2024-04-11 17:04 UTC, ztpn commented
> also the ranks has to be adjusted

yes, hls should be ramked above mp4
and add CORS_ALLOWED to mp4 and the source scraper

2024-04-12 13:53 UTC, JorrinKievit approved these changes

2024-04-12 15:37 UTC, merged