added vidsrc.to scraper with vidplay embed
movie-web/providers pull request #38
Opened 2023-12-14 07:23 UTC by Aijazmakerb

``This pull request resolves #XXX

 - [ ] I have read and agreed to the [code of conduct](https://github.com/movie-web/movie-web/blob/dev/.github/CODE_OF_CONDUCT.md).
 - [ ] I have read and complied with the [contributing guidelines](https://github.com/movie-web/movie-web/blob/dev/.github/CONTRIBUTING.md).
 - [ ] What I'm implementing was assigned to me and is an [approved issue](https://github.com/movie-web/movie-web/issues?q=is%3Aopen+is%3Aissue+label%3Aapproved). For reference, please take a look at our [GitHub projects](https://github.com/movie-web/movie-web/projects).
 - [ ] I have tested all of my changes.

###Changes

- Added [https://vidsrc.to/](url) source provider, both movies and TV shows
- Added [https://vidplay.site/](url) as VidStream embed provider

2023-12-14 17:29 UTC, mrjvs requested changes

2023-12-14 17:29 UTC, mrjvs commented on package-lock.json
please don't delete our lock file

2023-12-14 17:29 UTC, mrjvs commented on src/providers/embeds/vidplay.ts
> +  const responseText = await response.text();
please use ctx.fetcher() for requests that are possible for a browser to make.

Since this needs a custom referer. You will need to use ctx.proxiedFetcher() instead.

2023-12-14 17:29 UTC, mrjvs commented on src/providers/embeds/vidplay.ts
> +  const response = await fetch('https://raw.githubusercontent.com/Claudemirovsky/worstsource-keys/keys/keys.json');
Use ctx.fetcher(). dont use global fetch

2023-12-14 17:29 UTC, mrjvs commented on src/providers/embeds/vidplay.ts
> +    const key = await encodeId(ctx.url.split('/e/')[1].split('?')[0]);
Use `new Url(...)` for parsing things out of urls. You will be able to get the search parameter from there,

2023-12-14 17:29 UTC, mrjvs commented on src/providers/embeds/vidplay.ts
> +      const subtitleLink = ctx.url.split('?sub.info=')[1].split('&')[0];
Use `new Url(...)` for parsing things out of urls.

2023-12-14 17:29 UTC, mrjvs commented on src/providers/embeds/vidplay.ts
> +      const subtitlesFetch = await fetch(decodeURIComponent(subtitleLink));
use ctx.fetcher for browser possible requests, or ctx.proxiedFetcher

2023-12-14 17:29 UTC, mrjvs commented on src/providers/embeds/vidplay.ts
> +      `https://vidplay.site/mediainfo/${data}?${ctx.url.split('?')[1]}&autostart=true`,
Use new Url(...) for parsing things out of urls.

2023-12-14 17:29 UTC, mrjvs commented on src/providers/embeds/vidplay.ts
> +      `https://vidplay.site/mediainfo/${data}?${ctx.url.split('?')[1]}&autostart=true`,
And also put the other query parameters in the options as well, not just the v parameter

2023-12-14 17:36 UTC, mrjvs requested changes

2023-12-14 17:36 UTC, mrjvs commented on src/providers/sources/vidsrc/index.ts
> +  flags: [flags.NO_CORS],
Since vidplay cannot serve content with NO_CORS. this flag will also need to be removed from vidsrc

2023-12-15 05:14 UTC, Aijazmakerb commented on src/providers/embeds/vidplay.ts
> +    const key = await encodeId(ctx.url.split('/e/')[1].split('?')[0]);
There is not any parameter so cannot use new URL, only this method can work

2023-12-18 23:21 UTC, mrjvs commented
Since there has been no communication back yet, I'll be closing this PR. If you get back to working on it, you can make a new PR for it.

2023-12-18 23:21 UTC, closed without merging

2023-12-29 20:51 UTC, kaorlol commented
so you also take code and dont even start the repo?

2023-12-29 20:53 UTC, mrjvs commented
> so you also take code and dont even start the repo?

Stop just making uncessary drama, just post the source and we can take a look.

2023-12-29 20:53 UTC, kaorlol commented
alright https://github.com/Ciarands/vidsrc-to-resolver