Smashystream scraper
movie-web/providers pull request #43
Opened 2023-12-17 15:31 UTC by JorrinKievit

Based on https://github.com/JorrinKievit/restreamer/tree/main/src/main/extractors/smashystream. 

Completely missed the comment made on the issue in my repo 😅 -> https://github.com/JorrinKievit/restreamer/issues/8
Could start slowly phasing out my extractor/scraper logic and replace it with the package in here once we have added more providers.

- Added SmashyStream scraper for Player F and D (Player S is the movie-web embed 😉 )
- created a universal MovieScrapeContext and ShowScrapeContext. Saw it discussed in an older PR but since i also needed this type I thought I might as well add it.

Not too sure about the ranking, so it might be a bit random 😄 

 - [x] I have read and agreed to the [code of conduct](https://github.com/movie-web/movie-web/blob/dev/.github/CODE_OF_CONDUCT.md).
 - [x] I have read and complied with the [contributing guidelines](https://github.com/movie-web/movie-web/blob/dev/.github/CONTRIBUTING.md).
 - [ ] What I'm implementing was assigned to me and is an [approved issue](https://github.com/movie-web/movie-web/issues?q=is%3Aopen+is%3Aissue+label%3Aapproved). For reference, please take a look at our [GitHub projects](https://github.com/movie-web/movie-web/projects).
 - [x] I have tested all of my changes.

2023-12-17 15:41 UTC, JipFr commented on src/providers/embeds/smashystream/video1.ts
> +  name: 'SmashyStream (F)',
The names should not have these suffixes, should they?

2023-12-17 16:24 UTC, mrjvs commented
Hey, thanks for the PR. Looks good from a glance.
I'll give it a proper test and review another time, when I'm at my home pc.

In the meantime, can I invite you to our discord server so we can have a chat? It's over at https://discord.movie-web.app

2023-12-18 18:54 UTC, mrjvs requested changes
Looks good, works well.

Just a few pointers for the captions and then should be good for merge

2023-12-18 18:54 UTC, mrjvs commented on src/providers/embeds/smashystream/video1.ts
> +  name: 'SmashyStream (F)',
I think it's fine in this case, cuz they are embeds that don't really have any other proper name and can only work for smashystream

2023-12-18 18:54 UTC, mrjvs commented on src/providers/embeds/smashystream/video1.ts
> +                language,
language should be turned into a language code. If you don't have one available we can do "english name to code" conversion with `labelToLanguageCode()`.

2023-12-18 18:54 UTC, mrjvs commented on src/providers/embeds/smashystream/video1.ts
> +                kind: 'subtitles',
the field `kind` doesn't exist on our type, you can safely remove it

2023-12-18 18:54 UTC, mrjvs commented on src/providers/embeds/smashystream/video1.ts
> +                type: url.includes('.vtt') ? 'vtt' : 'srt',
You should be able to use `getCaptionTypeFromUrl()` instead of testing for it yourself.

2023-12-18 18:54 UTC, mrjvs commented on src/providers/sources/smashystream/index.ts
> +  rank: 400,
Let's start it out with a rank of 70. We can raise it if it turns out to be stable in production.

2023-12-18 19:47 UTC, JorrinKievit commented on src/providers/embeds/smashystream/video1.ts
> +                language,
Aah oki, maybe languageCode might make more sense? But out of the scope for this PR 😄

2023-12-18 19:48 UTC, mrjvs commented on src/providers/embeds/smashystream/video1.ts
> +                language,
maybe, but itll have to wait for next major version, a field rename like this is part of the external API, so it can break implementations.

2023-12-18 19:56 UTC, JorrinKievit commented
Everything should be resolved @mrjvs 🥳

2023-12-18 20:11 UTC, JorrinKievit commented on src/providers/embeds/smashystream/video1.ts
> +                language,
Yep makes sense!

2023-12-18 20:16 UTC, JorrinKievit commented on src/providers/embeds/smashystream/video1.ts
> +                type: getCaptionTypeFromUrl(url) ?? 'vtt',
Hmmm ye i agree its better to filter them out

2023-12-18 21:31 UTC, mrjvs approved these changes

2023-12-18 21:32 UTC, mrjvs commented
Thanks for the PR, after merge it won't directly be made into a release.
we're working on optimizing our frontend proxy requests right now, after that's done Ill make it a release.

Should only take a few days.

2023-12-18 21:32 UTC, merged