Added rezkaHD source
movie-web/providers pull request #49
Opened 2023-12-27 01:19 UTC by dqvist12

Added rezka.ag source

 - [X] I have read and agreed to the [code of conduct](https://github.com/movie-web/movie-web/blob/dev/.github/CODE_OF_CONDUCT.md).
 - [X] I have read and complied with the [contributing guidelines](https://github.com/movie-web/movie-web/blob/dev/.github/CONTRIBUTING.md).
 - [X] I have tested all of my changes.

2023-12-27 12:51 UTC, JipFr requested changes

2023-12-27 12:51 UTC, JipFr commented on src/providers/sources/rezka.ts
> +}
All interfaces should be grouped together near the top, below the imorts

2023-12-27 12:51 UTC, JipFr commented on src/providers/sources/rezka.ts
> +      const [, url, , titleAndYear] = match;
Perhaps this would be cleaner if you did the following instead? It doesn't bother me for the other ones, but this one is a bit more complex than those.

```suggestion
      const url = match[1];
      const titleAndYear = match[3];
```

2023-12-27 12:51 UTC, JipFr commented on src/providers/sources/rezka.ts
> +      match = itemRegex.exec(searchData);
Is there a reason you're reassigning `match` here?

2023-12-27 12:51 UTC, JipFr commented on src/providers/sources/rezka.ts
> +        flags: [flags.NO_CORS],
`NO_CORS` has recently been renamed `CORS_ALLOWED`

2023-12-27 12:51 UTC, JipFr commented on src/providers/sources/rezka.ts
> +        flags: [flags.NO_CORS],
See other comment on `NO_CORS`

2023-12-27 12:51 UTC, JipFr commented on src/providers/sources/rezka.ts
> +};
Perhaps add a comment explain just what "trash" is?

2023-12-27 12:51 UTC, JipFr commented on src/providers/sources/rezka.ts
> +
Please resolve the linting errors for the imports

2023-12-27 15:23 UTC, binaryoverload requested changes

2023-12-27 15:23 UTC, binaryoverload commented on src/providers/sources/rezka.ts
> +        'Content-Length': new URLSearchParams(requestData).toString().length.toString(),
These headers should be added automatically. Is there a reason why we're specifying them manually?

2023-12-27 22:09 UTC, mrjvs requested changes
As if two reviews isn't enough, here is another one.

2023-12-27 22:09 UTC, mrjvs commented on src/providers/sources/rezka.ts
> +        'Content-Length': new URLSearchParams(requestData).toString().length.toString(),
Correct, if you just give the URLSearchParams as body. All the headers will be set correctly.

2023-12-27 22:09 UTC, mrjvs commented on src/providers/sources/rezka.ts
> +    const response = await ctx.proxiedFetcher<string>(`${rezkaBase}/ajax/get_cdn_series/`, {
use the baseUrl option of the fetcher

2023-12-27 22:09 UTC, mrjvs commented on src/providers/sources/rezka.ts
> +    return jsonResponse;
json will also be parsed by the fetcher, so no need to do any of this either.

2023-12-27 22:09 UTC, mrjvs commented on src/providers/sources/rezka.ts
> +    throw new NotFoundError('No result found');
Please don't do a wildcard error like this. actually check something before throwing NotFoundError. and give it a descriptive message

2023-12-27 22:09 UTC, mrjvs commented on src/providers/sources/rezka.ts
> +      episode: ctx.media.episode.number || ctx.media.episode,
I think this might be a mistake. this will either be a number or an object with number.
If this isn't a mistake, make sure you copy the fields you need explicitly into an object. Otherwise if we ever change the input structure this can break for the scraper.

2023-12-27 22:09 UTC, mrjvs commented on src/providers/sources/rezka.ts
> +      result[numericQuality] = { type: 'mp4', url: m3u8Url.replace(/:hls:manifest\.m3u8$/, '') };
Check the qualities you want to extract expliticly, we don't want uncontrolled outputs going to the library users.
Also it shouldn't be a number map, it must be strings. Check `providers/streams.ts#Qualities` for the possibilties of the output qualities.

2023-12-29 02:35 UTC, TheScreechingBagel commented
hdrezka poggers

2023-12-29 22:17 UTC, closed without merging

2023-12-30 05:22 UTC, TheScreechingBagel commented
wait why closed

2024-01-21 04:14 UTC, MemeCornucopia commented
What happened to this