Port Providers
movie-web/providers pull request #5
Opened 2023-09-12 03:43 UTC by zisra

This pull request resolves [#435](https://github.com/movie-web/movie-web/issues/435)

providers need to be ported to the new provider repo:

* [ ]  superstream
* [x]  flixhq
* [ ]  gomovies
* [ ]  kissasian
* [x]  remotestream

embeds:

* [x]  upcloud
* [ ]  mp4upload
* [ ]  playm4u
* [ ]  streamm4u
* [ ]  streamsb

2023-09-14 07:41 UTC, mrjvs commented
@castdrian while I appreciate the enthusiasm. This is a draft PR and no review has been requested yet.
Both requested changes were present in the old provider code. which is being ported, so makes sense it'll still be present.

also you can't just change an external URL and expect it to work, urls are case sensitive.

2023-09-14 07:42 UTC, mrjvs commented on src/providers/sources/remotestream/index.ts
> +  name: 'Remote Stream',
ported from original code, shouldn't be changed

2023-09-14 07:44 UTC, castdrian commented
> @castdrian while I appreciate the enthusiasm. This is a draft PR and no review has been requested yet. Both requested changes were present in the old provider code. which is being ported, so makes sense it'll still be present.
> 
> also you can't just change an external URL and expect it to work, urls are case sensitive.

I don't see how fixing the casing in the variable name would affect the string content

2023-09-14 07:46 UTC, mrjvs commented
Yea my bad, I misinterpreted. I thought you meant changing `/../Shows/.../....m3u8` to `/.../shows/.../....m3u8` but you were talking about the variable name.

while I agree with the change, I still don't think we should review before they've asked for it. its quite clearly still in progress.

2023-09-15 18:01 UTC, mrjvs commented
ive put in some leg work myself, I've done all embed scrapers.

2023-09-15 19:01 UTC, zisra commented
Was just doing streamsb and mp4upload :/

2023-09-16 04:28 UTC, zisra commented
All done, just have not tested yet. Probably have a lot of inconsistencies. I already noticed one with arrow functions vs regular functions being used

2023-09-16 08:10 UTC, mrjvs commented
Nice, I'll take a look sometime this weekend.

2023-09-16 08:23 UTC, binaryoverload requested changes

2023-09-16 08:23 UTC, binaryoverload commented on .eslintrc.js
> +    'no-param-reassign': 'off',
Why has this rule been disabled? I would argue it should remain

2023-09-16 08:24 UTC, mrjvs commented on .eslintrc.js
> +    'no-param-reassign': 'off',
That was me. Lot of builtin js features go against this rule. Like .reduce()

2023-09-16 08:29 UTC, binaryoverload commented on .eslintrc.js
> +    'no-param-reassign': 'off',
Potentially replace with `no-param-reassign: ["error", { "props": false }]`?

This allows mutating of properties on a parameter, but not the parameter itself

2023-09-16 08:31 UTC, mrjvs commented on .eslintrc.js
> +    'no-param-reassign': 'off',
Sounds good. I'll commit that when I get to testing the code

2023-09-18 19:09 UTC, binaryoverload requested changes
Looks good, just an issue with GoMovies and RemoteStream

Tested:
 - SuperStream
 - Upcloud
 - FlixHQ
 - KissAsian (Doesn't work)

2023-09-18 19:32 UTC, mrjvs requested changes

2023-09-18 19:32 UTC, mrjvs commented on src/providers/sources/gomovies/index.ts
> +    const search = await ctx.proxiedFetcher<any>(`${gomoviesBase}/ajax/search`, {
use baseUrl option instead of template literals

2023-09-18 19:32 UTC, mrjvs commented on src/providers/sources/gomovies/index.ts
> +    const seasons = await ctx.proxiedFetcher<any>(`${gomoviesBase}/ajax/v2/tv/seasons/${mediaId}`, {
use baseUrl option instead of template literals

2023-09-18 19:32 UTC, mrjvs commented on src/providers/sources/gomovies/index.ts
> +    const seasons = await ctx.proxiedFetcher<any>(`${gomoviesBase}/ajax/v2/tv/seasons/${mediaId}`, {
also instead of any, return string

2023-09-18 19:32 UTC, mrjvs commented on src/providers/sources/gomovies/index.ts
> +    const search = await ctx.proxiedFetcher<any>(`${gomoviesBase}/ajax/search`, {
also instead of any, return string

2023-09-18 19:32 UTC, mrjvs commented on src/providers/sources/gomovies/index.ts
> +    const episodes = await ctx.proxiedFetcher<any>(`${gomoviesBase}/ajax/v2/season/episodes/${targetSeason.dataId}`, {
use baseUrl option instead of template literals. also use string instead of any for return

2023-09-18 19:32 UTC, mrjvs commented on src/providers/sources/gomovies/index.ts
> +    const sources = await ctx.proxiedFetcher<any>(`${gomoviesBase}/ajax/v2/episode/servers/${mediaId}`, {
use baseUrl option instead of template literals. also use string instead of any for return

2023-09-18 19:32 UTC, mrjvs commented on src/providers/sources/gomovies/index.ts
> +    const search = await ctx.proxiedFetcher<any>(`${gomoviesBase}/ajax/search`, {
use baseUrl option instead of template literals. also use string instead of any for return

2023-09-18 19:32 UTC, mrjvs commented on src/providers/sources/gomovies/source.ts
> +  }>(`${gomoviesBase}/ajax/sources/${upcloudDataId}`, {
use baseUrl option instead of template literals.

2023-09-18 19:32 UTC, mrjvs commented on src/providers/sources/kissasian/getEmbeds.ts
> +      const watch = await ctx.proxiedFetcher<any>(`${kissasianBase}/${targetEpisode.url}&s=${provider.id}`);
use baseUrl option instead of template literals. also use string instead of any for return.
you should also use `query` option to set the provider ID. query parameters are merged with the inputted url

2023-09-18 19:32 UTC, mrjvs commented on src/providers/sources/kissasian/index.ts
> +    const drama = await ctx.proxiedFetcher<any>(targetDrama.url);
use string instead of any for return

2023-09-18 19:32 UTC, mrjvs commented on src/providers/sources/kissasian/index.ts
> +    const drama = await ctx.proxiedFetcher<any>(targetDrama.url);
use string instead of any for return

2023-09-18 19:32 UTC, mrjvs commented on src/providers/sources/kissasian/search.ts
> +  const searchResults = await ctx.proxiedFetcher<any>('/Search/SearchSuggest', {
use string instead of any for return

2023-09-18 19:32 UTC, mrjvs commented on src/providers/sources/superstream/sendRequest.ts
> +    body: `${formatted.toString()}&token${nanoid()}`,
If you put in the formatted variable, it will automatically set the content type header and will put it into the body automatically.

so just do `formatted.append("token", nanoid())` and then `body: formatted`

2023-09-18 20:03 UTC, zisra commented on src/providers/sources/kissasian/index.ts
Can you give me some code I can use to test the providers please> Otherwise I cannot debug

2023-09-27 17:43 UTC, zisra commented
Not sure if kissasian should be removed or somehow fixed, but I cannot fix it because they made some kind of breaking changes. I tried my best but I feel like it's "out of scope" to this PR anyways 🫡

2023-09-27 17:51 UTC, binaryoverload commented
> Not sure if kissasian should be removed or somehow fixed, but I cannot fix it because they made some kind of breaking changes. I tried my best but I feel like it's "out of scope" to this PR anyways 🫡

Agreed, out of scope. I have disabled and will merge this PR. Thanks for the work

2023-09-27 17:53 UTC, binaryoverload approved these changes

2023-09-27 17:54 UTC, merged

2023-09-27 19:36 UTC, zisra commented
706948500197212240