VidSrcTo with Vidplay and Filemoon embed
movie-web/providers pull request #50
Opened 2023-12-27 19:39 UTC by JorrinKievit

In continuation of #38 . Also added Filemoon, the second provider of VidSrcTo.
Vidplay cannot be played in the browser (CORS restriction), but Filemoon can.

 - [x] I have read and agreed to the [code of conduct](https://github.com/movie-web/movie-web/blob/dev/.github/CODE_OF_CONDUCT.md).
 - [x] I have read and complied with the [contributing guidelines](https://github.com/movie-web/movie-web/blob/dev/.github/CONTRIBUTING.md).
 - [ ] What I'm implementing was assigned to me and is an [approved issue](https://github.com/movie-web/movie-web/issues?q=is%3Aopen+is%3Aissue+label%3Aapproved). For reference, please take a look at our [GitHub projects](https://github.com/movie-web/movie-web/projects).
 - [x] I have tested all of my changes.

2023-12-27 20:04 UTC, binaryoverload requested changes

2023-12-27 20:04 UTC, binaryoverload commented on src/providers/sources/vidsrcto/common.ts
> +  const binaryData = Buffer.from(standardizedInput, 'base64').toString('binary');
Will this `Buffer` code be compatible with the browser? I'm unsure if Vite does any transformations here

2023-12-27 20:04 UTC, binaryoverload commented on src/providers/sources/vidsrcto/common.ts
> +  return decodeURIComponent(decodeURIComponent(decodedText));
Just to check, is running the decode function twice intentional?

2023-12-27 20:06 UTC, JorrinKievit commented on src/providers/sources/vidsrcto/common.ts
> +  return decodeURIComponent(decodeURIComponent(decodedText));
Yes it is intentional. And no, I don't know why it's encoded twice here 😂

2023-12-27 20:07 UTC, binaryoverload commented on src/providers/sources/vidsrcto/common.ts
> +  return decodeURIComponent(decodeURIComponent(decodedText));
Fair enough 😂

2023-12-27 20:07 UTC, JorrinKievit commented on src/providers/sources/vidsrcto/common.ts
> +  const binaryData = Buffer.from(standardizedInput, 'base64').toString('binary');
Hmmm good question, not sure

2023-12-27 20:14 UTC, binaryoverload approved these changes

2023-12-27 20:15 UTC, JorrinKievit commented on src/providers/sources/vidsrcto/common.ts
> +  const binaryData = Buffer.from(standardizedInput, 'base64').toString('binary');
Buffer, wasnt even needed here. So removed it :D

2023-12-27 20:16 UTC, binaryoverload commented on src/providers/sources/vidsrcto/common.ts
> +  const binaryData = Buffer.from(standardizedInput, 'base64').toString('binary');
Perfect!

2023-12-27 21:57 UTC, mrjvs requested changes

2023-12-27 21:57 UTC, mrjvs commented on src/providers/sources/vidsrcto/index.ts
> +      : `${vidSrcToBase}}/embed/tv/${imdbId}/${ctx.media.season.number}/${ctx.media.episode.number}`;
There's a double curly bracket here.
Also it's probably better to set the baseUrl on the fetcher instead of appending it here.

2023-12-27 21:57 UTC, mrjvs commented on src/providers/sources/vidsrcto/index.ts
> +  rank: 400,
This currently marked as not CORS_ALLOWED. meaning it can't be used in the browser.
However from the code it seems that it may work if we slap in some proxiedFetchers.
Is there a reason why it's not for browser that im missing?

2023-12-27 21:57 UTC, mrjvs commented on src/providers/embeds/vidplay/common.ts
> +  return `${vidplayBase}/mediainfo/${fuToken}${new URL(ctx.url).search}&autostart=true`;
This feel fragile with string interpolation. You can use `makeFullUrl` to append a base url and a normal url.
It will merge base url with partial url, and it will merge search params with its options.

2023-12-27 22:19 UTC, JorrinKievit commented on src/providers/sources/vidsrcto/index.ts
> +  rank: 400,
Nope forgot to change from the original PR. Since Vidplay cant be played in the browser. But filemoon can so will change tmrow

2023-12-27 22:20 UTC, JorrinKievit commented on src/providers/sources/vidsrcto/index.ts
> +      : `${vidSrcToBase}}/embed/tv/${imdbId}/${ctx.media.season.number}/${ctx.media.episode.number}`;
Oof good eye

2023-12-28 17:41 UTC, JorrinKievit commented
There was no implementation for retrieving the imdb from shows (Oops, should've tested). So I copied over the implementation from #42 since I assume this one gets merged earlier. Rest of the feedback should be fixed 👍

2023-12-29 20:28 UTC, kaorlol commented
So you take someones work and dont even start their repo?

2024-01-01 09:31 UTC, mrjvs commented
> I got sent a quote from the original creator. Since we've limited github activity to only contributors, I'm posting it in their behalf:

Hey, tysm for the credit!
Just had a chance to look over the PR and I just wanted to note a few things for you.

- keyPermutation is totally unnecessary, this is based on my key_permutation function, I implemented this twice while testing and just forgot to remove it, this is the same as decode with slight changes, you can just modify the initial decode function and use that instead.
- getEncodedId can just use decode and will be cross-platform compatible.
- keys are different across different embed.js file versions, claude uses vidplay.lol as the base url to fetch the keys, you're using vidplay.site with these vidplay.lol keys. Currently the same key is used across all hosts and while I highly doubt they will ever use different embed.js versions across the different hosts (vidplay.site, vidplay.online, vidplay.lol), this could be a potential issue/detection vector in future.

I didn't expect so many people to also want to use this source when I made my resolver and so the first release was a (not great) initial mock-up.
I'm in the process of writing an AST parser that reconstructs the necessary key strings, just gotta find time to finish it up (should hopefully be soon), but this will mean that that last point is a non-issue and also you wont run into any issues with the keys being invalid when using this source,
Since so many people were using my work as reference I completely rewrote everything yesterday to fix some glaring issues, feel free to use the updated repo as reference to make any necessary changes.

2024-01-04 19:27 UTC, kaorlol commented
> > I got sent a quote from the original creator. Since we've limited github activity to only contributors, I'm posting it in their behalf:
> 
> Hey, tysm for the credit!
> Just had a chance to look over the PR and I just wanted to note a few things for you.
> 
> - keyPermutation is totally unnecessary, this is based on my key_permutation function, I implemented this twice while testing and just forgot to remove it, this is the same as decode with slight changes, you can just modify the initial decode function and use that instead.
> - getEncodedId can just use decode and will be cross-platform compatible.
> - keys are different across different embed.js file versions, claude uses vidplay.lol as the base url to fetch the keys, you're using vidplay.site with these vidplay.lol keys. Currently the same key is used across all hosts and while I highly doubt they will ever use different embed.js versions across the different hosts (vidplay.site, vidplay.online, vidplay.lol), this could be a potential issue/detection vector in future.
> 
> I didn't expect so many people to also want to use this source when I made my resolver and so the first release was a (not great) initial mock-up.
> I'm in the process of writing an AST parser that reconstructs the necessary key strings, just gotta find time to finish it up (should hopefully be soon), but this will mean that that last point is a non-issue and also you wont run into any issues with the keys being invalid when using this source,
> Since so many people were using my work as reference I completely rewrote everything yesterday to fix some glaring issues, feel free to use the updated repo as reference to make any necessary changes.

Btw I didn't mean to be a dick when I sent the thing looking for credit for him. He's one of my friends in discord and I should've worded it better.

2024-01-05 18:48 UTC, mrjvs requested changes

2024-01-05 18:48 UTC, mrjvs commented on src/providers/sources/vidsrcto/index.ts
> +  flags: [flags.CORS_ALLOWED],
I think we should remove the flag here, since it can only return embeds that are cors locked. so scraping this is not benefical to the browser to get cors allowed streams.

2024-01-05 19:05 UTC, mrjvs approved these changes

2024-01-06 14:41 UTC, merged