Added ridomovies with Ridoo and Closeload embed
movie-web/providers pull request #52
Opened 2023-12-29 18:33 UTC by JorrinKievit

This pull request resolves multiple discord requests 😄 

This site has 2 embeds:
- Ridoo.net
       - Present on TV Shows
       - Can be played in the browser (tested).
       - One issue, the captions are baked in the HLS URL. The player does display them, but the captions selector does not 
          support this. Not sure how to approach yet. It does show the first caption by default.
![image](https://github.com/movie-web/providers/assets/43169049/ba40151d-cb21-4c80-96b1-93db2d964f4d)

- Closeload
      - Present on Movies
      - IP Locked, cant be used until the extension is ready.

I tried testing them in the browser CLI, but I'm getting insta blocked by puppeteer. Might be related to the issues occurring in #47. So I'm not sure if cloudflare immediately recognizes puppeteer, and blocks it. I am proxying the requests 🤔 . So unsure on how both embeds will behave in the browser.

 - [x] I have read and agreed to the [code of conduct](https://github.com/movie-web/movie-web/blob/dev/.github/CODE_OF_CONDUCT.md).
 - [x] I have read and complied with the [contributing guidelines](https://github.com/movie-web/movie-web/blob/dev/.github/CONTRIBUTING.md).
 - [ ] What I'm implementing was assigned to me and is an [approved issue](https://github.com/movie-web/movie-web/issues?q=is%3Aopen+is%3Aissue+label%3Aapproved). For reference, please take a look at our [GitHub projects](https://github.com/movie-web/movie-web/projects).
 - [x] I have tested all of my changes.

2024-01-03 12:58 UTC, JorrinKievit commented
Looked into it a bit. Getting blocked by Cloudflare WAF if the request is sent from the worker. It seems like it simply checks on the referer header, because if that is removed I'm getting the same blocked page in Node. But from the worker it is blocked regardless of the header 🤔 . For now I'll put it as IP_LOCKED.

2024-01-04 20:22 UTC, JorrinKievit commented
The issue was related to an issue in the proxy server. Since that is fixed the Ridoo embed is functional, aside from the captions issue in the video player.

![image](https://github.com/movie-web/providers/assets/43169049/1bdb0bdf-cab1-45dc-b11a-126cdd6e3494)

2024-01-05 19:03 UTC, mrjvs requested changes

2024-01-05 19:03 UTC, mrjvs commented on src/providers/embeds/ridoo.ts
> +      .html();
It errors with not being able to find the eval code

2024-01-05 19:03 UTC, mrjvs commented on src/providers/sources/ridomovies/index.ts
> +      q: encodeURIComponent(ctx.media.title),
This will doubl encode the title. is that intentional?

2024-01-05 19:03 UTC, mrjvs commented on src/providers/sources/ridomovies/index.ts
> +  const show = searchResult.data.items[0];
if it cant find the item. it should throw a NotFoundError(). so library can handle errors and not having items seperately

2024-01-05 19:03 UTC, mrjvs commented on src/providers/sources/ridomovies/index.ts
> +  rank: 500,
Let's rank it a bit lower, lets place it right below flixhq

2024-01-05 19:37 UTC, JorrinKievit commented on src/providers/embeds/ridoo.ts
> +      .html();
Oooh the page has changed (no longer even have to eval, the url is just there lol)

2024-01-27 22:28 UTC, mrjvs requested changes
Sorry about the delay in reviewing. Found two more points, then it should be ready to merge.

2024-01-27 22:28 UTC, mrjvs commented on src/providers/embeds/closeload.ts
> +          flags: [flags.IP_LOCKED],
Referer is required for this source. Please add the requiredHeaders field for it.

2024-01-27 22:28 UTC, mrjvs commented on src/providers/embeds/closeload.ts
> +          hasCorsRestrictions: false,
hasCorsRestrictions needs to be true, it cannot be used without proxying

2024-01-27 22:28 UTC, mrjvs commented on src/providers/embeds/closeload.ts
> +  id: 'closeload',
seems to work with normal fetch and node-fetch but throws a NotFoundError when scraping with the browser cli fetcher. Maybe user agents?

2024-01-27 23:29 UTC, JorrinKievit commented on src/providers/embeds/closeload.ts
> +  id: 'closeload',
I think this is because the embed is filtered out in the browser scraper, since the embed does not have the flag CORS_ALLOWED. If I add this flag to the embed the scrape is successful with browser CLI

![image](https://github.com/movie-web/providers/assets/43169049/5f8ef6af-2936-46ed-b3ab-eda88ae48501)

2024-01-28 20:22 UTC, mrjvs commented on src/providers/embeds/closeload.ts
> +  id: 'closeload',
You're absolutely right, my bad.

2024-01-28 20:23 UTC, mrjvs approved these changes

2024-01-28 20:23 UTC, merged