Hd rezka
movie-web/providers pull request #55
Opened 2023-12-29 22:28 UTC by dqvist12

Hd rezka scraper

- Hd rezka - A great source provider, both movies and TV shows in 4k

 - [x] I have read and agreed to the [code of conduct](https://github.com/movie-web/movie-web/blob/dev/.github/CODE_OF_CONDUCT.md).
 - [x] I have read and complied with the [contributing guidelines](https://github.com/movie-web/movie-web/blob/dev/.github/CONTRIBUTING.md).
 - [ ] What I'm implementing was assigned to me and is an [approved issue](https://github.com/movie-web/movie-web/issues?q=is%3Aopen+is%3Aissue+label%3Aapproved). For reference, please take a look at our [GitHub projects](https://github.com/movie-web/movie-web/projects).
 - [x] I have tested all of my changes.

2023-12-30 21:03 UTC, jevinruv commented
@dqvist12 did you get it to play from this source? doenst work with movie-web proj when i run locally

2023-12-31 18:09 UTC, JipFr requested changes
Perhaps some of the utility functions should be moved into separate files to make the main file more clear and easy to read?

2023-12-31 18:09 UTC, JipFr commented on src/providers/sources/rezka.ts
> +  async scrapeMovie(ctx: any) {
```suggestion
  async scrapeMovie(ctx) {
```

2023-12-31 18:09 UTC, JipFr commented on src/providers/sources/rezka.ts
> +  async scrapeShow(ctx: any) {
```suggestion
  async scrapeShow(ctx) {
```

2024-01-03 22:45 UTC, JorrinKievit commented on src/providers/sources/rezka/index.ts
> +    const response = await ctx.proxiedFetcher<any>('/ajax/get_cdn_series/', {
Same here

2024-01-03 22:45 UTC, JorrinKievit commented on src/providers/sources/rezka/index.ts
> +async function getStream(requestData: any, ctx: ScrapeContext): Promise<any> {
Could we type this instead of "any" ?

2024-01-03 22:45 UTC, JorrinKievit commented on src/providers/sources/rezka/index.ts
> +export const rezkaScraper = makeSourcerer({
Since both scrapeShow and movieShow are quite similar. We can turn this into one function called "universalScraper". We do this more often throughout this repo.

And do something like this:
```
 const requestData = {
      id: movieReturn?.id,
      translator_id: 238,
      season: type === "show" ? seasonNumber : 1,
      episode: type === "show ? episodeNumber : 1,
      favs: generateUUID(),
      action: type === "show" ? "get_episodes : "get_movie"
    };
```

2024-01-03 22:45 UTC, JorrinKievit commented on src/providers/sources/rezka/index.ts
> +    console.log('ctx', ctx);
console log left :D

2024-01-05 19:18 UTC, mrjvs requested changes

2024-01-05 19:18 UTC, mrjvs commented on src/providers/sources/rezka/index.ts
> +    });
use the ops.query parameter to set query parameters. you will not need to encode it them.

2024-01-05 19:18 UTC, mrjvs commented on src/providers/sources/rezka/index.ts
> +  }
NotFoundErrors should only ever be used when you are very sure the content is not found. Not used as a catch all for failing to parse data.

2024-01-05 19:18 UTC, mrjvs commented on src/providers/sources/rezka/index.ts
> +  }
This applies throughout the entire file, not just here

2024-01-05 19:18 UTC, mrjvs commented on src/providers/sources/rezka/index.ts
> +async function getStream(requestData: RequestData, ctx: ScrapeContext): Promise<any> {
No `Promise<any>` please

2024-01-05 19:18 UTC, mrjvs commented on src/providers/sources/rezka/index.ts
> +      },
URLSearchParams are already parsed as x-www-form-encoded. So no need to set content type or stringify the params. just pass it in.

2024-01-05 19:18 UTC, mrjvs commented on src/providers/sources/rezka/index.ts
> +    return JSON.parse(response);
JSON is already parsed if the correct header is sent back from the server. do you need to do this?

2024-01-05 19:18 UTC, mrjvs commented on src/providers/sources/rezka/utils.ts
> +export { clearTrash, extractTitleAndYear, parseSubtitleLinks, parseVideoLinks, generateUUID };
Use export keyword in front of parts you want to export. not as final statement

2024-01-05 19:18 UTC, mrjvs commented on src/providers/sources/rezka/index.ts
> +    favs: generateUUID(), // Random UUID
This doesn't actually make uuid's, so recommend naming the function `generateUUIDLike()`

2024-01-05 19:18 UTC, mrjvs commented on src/providers/sources/rezka/utils.ts
> +      return '1440';
don't return the quality if it doesn't exist in the quality enum. things will break

2024-01-05 19:18 UTC, mrjvs commented on src/providers/sources/rezka/utils.ts
> +function mapNumericQualityToQualities(numericQuality: number): string {
make the return type `Qualities`. import it from the stream file or something like it.

2024-01-05 19:18 UTC, mrjvs commented on src/providers/sources/rezka/utils.ts
> +  console.log(inputString);
no logs please

2024-01-05 19:18 UTC, mrjvs commented on src/providers/sources/rezka/utils.ts
> +// Removes 'trash' from the getStream() response and decodes it
what is "trash" in this context?

2024-01-27 22:34 UTC, mrjvs commented
Since there hasn't been any response from review comments, im gonna close this PR. feel free to open another one once the review comments have been addressed

2024-01-27 22:34 UTC, closed without merging