spelling/grammar
movie-web/providers pull request #56
Opened 2023-12-31 04:01 UTC by systemcrash

This pull request improves docs

 - [X] I have read and agreed to the [code of conduct](https://github.com/movie-web/movie-web/blob/dev/.github/CODE_OF_CONDUCT.md).
 - [X] I have read and complied with the [contributing guidelines](https://github.com/movie-web/movie-web/blob/dev/.github/CONTRIBUTING.md).
 - [ ] What I'm implementing was assigned to me and is an [approved issue](https://github.com/movie-web/movie-web/issues?q=is%3Aopen+is%3Aissue+label%3Aapproved). For reference, please take a look at our [GitHub projects](https://github.com/movie-web/movie-web/projects).
 - [ ] I have tested all of my changes.

2023-12-31 11:42 UTC, binaryoverload requested changes
Pretty good overall, just some changes I've spotted :D

2023-12-31 11:42 UTC, binaryoverload commented on .docs/content/1.get-started/1.quick-start.md
> +Now lets scrape an item:
```suggestion
Now let's scrape an item:
```

2023-12-31 11:42 UTC, binaryoverload commented on .docs/content/1.get-started/1.quick-start.md
> +Perfect. This instance of the providers you can reuse everywhere.
```suggestion
Perfect. You now have an instance of the providers you can reuse everywhere.
```

2023-12-31 11:42 UTC, binaryoverload commented on .docs/content/2.essentials/3.customize-providers.md
> +You make provider controls in two ways. Either with `makeProviders()` (the simpler option) or with `buildProviders()` (more elaborate and extensive option).
```suggestion
You make the provider controls in two ways. Either with `makeProviders()` (the simpler option) or with `buildProviders()` (more elaborate and extensive option).
```

2023-12-31 11:42 UTC, binaryoverload commented on .docs/content/5.api-reference/5.ProviderControlslistEmbeds.md
> +// Guaranteed to return only type: 'embed'
```suggestion
// Guaranteed to only return the type: 'embed'
```

2023-12-31 11:46 UTC, mrjvs submitted a review, later dismissed

2023-12-31 11:46 UTC, mrjvs commented on .docs/content/2.essentials/2.fetchers.md
> +When creating provider controls, configure a fetcher.
I'm not sure about this change, please revert

2023-12-31 12:28 UTC, systemcrash commented on .docs/content/2.essentials/3.customize-providers.md
> +You make provider controls in two ways. Either with `makeProviders()` (the simpler option) or with `buildProviders()` (more elaborate and extensive option).
I think the abstract (sans the) works best. But OK.

2023-12-31 12:30 UTC, systemcrash commented on .docs/content/5.api-reference/5.ProviderControlslistEmbeds.md
> +// Guaranteed to return only type: 'embed'
`to x verb` == split infinitive. I can do:

Guaranteed to return only the type:

2023-12-31 12:31 UTC, systemcrash commented on .docs/content/2.essentials/2.fetchers.md
> +When creating provider controls, configure a fetcher.
The net effect is the same. This way it avoids the awkward "it will need you". Please reword.

2023-12-31 12:32 UTC, mrjvs commented on .docs/content/2.essentials/2.fetchers.md
> +When creating provider controls, configure a fetcher.
Either revert or make it better. But just saying "configure a fetcher" is weird

2023-12-31 12:33 UTC, systemcrash commented on .docs/content/2.essentials/2.fetchers.md
> +When creating provider controls, configure a fetcher.
"configure a fetcher also. "?

2023-12-31 12:36 UTC, binaryoverload commented on .docs/content/5.api-reference/5.ProviderControlslistEmbeds.md
> +// Guaranteed to return only type: 'embed'
I stand by my suggestion, a split infinitive isn't always bad

https://en.wikipedia.org/wiki/Split_infinitive#Current_views

2023-12-31 12:37 UTC, binaryoverload commented on .docs/content/2.essentials/2.fetchers.md
> +When creating provider controls, configure a fetcher.
```
When creating provider controls, a fetcher will need to be configured.
Depending on your environment, this can come with some considerations:
```

Perhaps?

2023-12-31 12:38 UTC, systemcrash commented on .docs/content/5.api-reference/5.ProviderControlslistEmbeds.md
> +// Guaranteed to return only type: 'embed'
When the meaning is clearer, yes. But syntactically, these remain identical. Still want it?

2023-12-31 12:40 UTC, binaryoverload commented on .docs/content/5.api-reference/5.ProviderControlslistEmbeds.md
> +// Guaranteed to return only type: 'embed'
Yes please, it reads more fluid imo

2023-12-31 12:43 UTC, systemcrash commented on .docs/content/2.essentials/2.fetchers.md
> +When creating provider controls, configure a fetcher.
Yeah that works. Although what is it you're trying to say? If the user or coder needs to do something, why not just get them doing it already?

2023-12-31 12:46 UTC, systemcrash commented on .docs/content/5.api-reference/5.ProviderControlslistEmbeds.md
> +// Guaranteed to return only type: 'embed'
I go along with "to boldly go" from star trek because I heard it so many times. But "to go boldly" helps translators and machine translation that doesn't know better. 

To only return it is, then. 😊

2023-12-31 12:51 UTC, systemcrash commented on .docs/content/2.essentials/2.fetchers.md
> +When creating provider controls, configure a fetcher.
altho the "need to" bit signals the 'mandatory' part.

2023-12-31 12:52 UTC, systemcrash commented on .docs/content/5.api-reference/5.ProviderControlslistEmbeds.md
> +// Guaranteed to return only type: 'embed'
How about simply: "Returns the type: "?

2024-01-01 23:45 UTC, mrjvs commented
Do not force push

2024-01-01 23:48 UTC, binaryoverload commented on .docs/content/5.api-reference/5.ProviderControlslistEmbeds.md
> +// Guaranteed to return only type: 'embed'
Please change to the suggestion, we would like the "guaranteed" to be in there to make it explicit.

2024-01-02 19:06 UTC, mrjvs commented
nice...
![https://i.imgur.com/i7QuezY.png](https://i.imgur.com/i7QuezY.png)

2024-01-06 14:45 UTC, binaryoverload approved these changes

2024-01-06 14:47 UTC, merged