Added source testing script
movie-web/providers pull request #6
Opened 2023-09-25 23:44 UTC by jonbarrow

@binaryoverload Said on Discord I didn't need an issue open for this one

 - [x] I have read and agreed to the [code of conduct](https://github.com/movie-web/movie-web/blob/dev/.github/CODE_OF_CONDUCT.md).
 - [x] I have read and complied with the [contributing guidelines](https://github.com/movie-web/movie-web/blob/dev/.github/CONTRIBUTING.md).
 - [x] I have tested all of my changes.

There is currently no way, provided by the repo, to test sources during development. This is aimed at making a system which can support this

Marking this as a draft for now since it needs changes, and as a first time contribution here I'm unsure if I followed everything to the preferred style

## Changes
Adds a `run-source.ts` script to test running specific sources. Script supports both providers and embed sources. The script also has 2 execution modes:

- CLI mode, for passing in arguments directly to the script
- Question mode, where the script asks you questions about which source you wish to test

## Issues
There are 2 big issues keeping this as a draft PR

1. Native `fetch` is not working when used with `makeStandardFetcher`. I know @mrjvs was talking about making `fetch` work with `node-fetch`, but I was unsure if this actually happened or not. The script does check which fetcher you want to use, but it only allows `node-fetch` for now
2. `node-fetch` was downgraded to v2. When using `node-fetch` 3+, `require() of ES Module` is thrown when importing. The TMDB API docs also still recommend using v2 and TMDB is what is used here from what I can tell, so this change shouldn't cause any issues?

I would rather not mark this as ready for review until these issues are either resolved or approved to be okay

## Screenshots
(some screenshots/gifs are from different versions, hence differing file names/paths, but the input/output is identical)

### CLI Mode
![Screenshot from 2023-09-25 18-06-25](https://github.com/movie-web/providers/assets/27011796/3970736d-4b7c-4e1b-b479-99ebd12e1d77)
![Peek 2023-09-25 18-07](https://github.com/movie-web/providers/assets/27011796/4e377761-98ae-40ba-a047-fe8fa0e70b1e)
![Peek 2023-09-25 18-07 2](https://github.com/movie-web/providers/assets/27011796/d7b73b1c-d160-489c-ba8f-fac53c192505)

### Question Mode
![Peek 2023-09-24 23-54](https://github.com/movie-web/providers/assets/27011796/acb6f301-9e44-4797-a64b-72b40d600c40)
![Peek 2023-09-24 23-55](https://github.com/movie-web/providers/assets/27011796/8988cd1a-3494-435b-8c0f-a418e917e031)

2023-09-26 06:15 UTC, mrjvs commented
Took a quick look, code lookin good.

Regarding the issues you mentioned:
1. The problems I mentioned with native fetch are afaik only in types. It hasnt been resolved, but theoretically you can just "as any" native fetch into it and it would work. I have no problem with keeping only node-fetch supported for now though.
2. I would prefer node-fetch to stay in v3. But the lib has certainly been a pain in the ass before. I'm gonna do some testing myself to see if I can get v3 to work. If I can't then we can just downgrade, shouldn't make much of a difference. I'll keep you updated on my progress with that.

2023-09-26 06:20 UTC, jonbarrow commented
Sounds good

1. I just tried `as any` and you're right it does work just fine. I'll go ahead and add this in. I'll leave a `TODO` though since `as any` sucks, imo
2. Thinking about it more since MW uses TMDB as it's data source, and they still recommend v2 in their own API docs (see screenshot), it might be better to just stick with that? Is there any clear advantage to moving to v3? Last I checked v2 was still getting security updates, just no new feature updates

![Screenshot from 2023-09-26 02-19-03](https://github.com/movie-web/providers/assets/27011796/e883e254-5c07-4793-917a-3631993bad97)

2023-09-26 06:30 UTC, mrjvs commented
1. Agreed, it sucks to cast any, haven't gotten around to make it properly work. Soon:tm: I guess. Todo is fine
2. My reason is that the eco system is moving to esm. Lots of packages are moving to esm-only, and I personally support that decision. (Thats the big difference between 2 and 3. 2 is cjs while 3 is esm, for the rest they work identically) Where possible I want to keep using esm packages. But again, if I can't get it working then v2 will work fine, just want to give it an attempt myself.

(That said, the output of the lib should work for both esm and cjs. We're not esm-only)

2023-09-26 06:35 UTC, binaryoverload approved these changes
Looks all good to me, thanks for the work!

2023-09-26 06:40 UTC, jonbarrow commented
I forgot to add the todo comment lmao. Oh well, gonna blame it on being 2am. I don't think it's worth adding another commit just for that

> My reason is that the eco system is moving to esm. Lots of packages are moving to esm-only, and I personally support that decision. (Thats the big difference between 2 and 3. 2 is cjs while 3 is esm, for the rest they work identically) Where possible I want to keep using esm packages. But again, if I can't get it working then v2 will work fine, just want to give it an attempt myself.

Very fair. I don't particularly have a strong stance for or against ESM, I just want my code To Work:tm:. So if that can happen with v3 I'm for it. My only concern would be moving too fast, since it seems like places are still recommending v2, but it's not a massive concern of mine. If it works, and isn't atrocious to maintain, that's all I care about at the end of the day

2023-09-26 17:01 UTC, mrjvs requested changes
nice work, thanks a lot.
just a few changes, im possibly a bit too nit picky 😄 

In my testing of node-fetch 3 vs 2. I did add a package.json script for the cli, so you can do `npm run test:dev` to start it.

as for the conclusion on node-fetch 3 vs 2. I didnt get it to work nicely either, so lets keep it at v2.

2023-09-26 17:10 UTC, jonbarrow commented on run-source.ts
`/src/cli.ts` makes it seem like more of a general purpose CLI tool for the library, but this is more geared towards use during development. I agree adding into `src` would fit but I'm not sure if `cli.ts` is the right choice?

2023-09-26 17:11 UTC, jonbarrow commented on run-source.ts
> +  }).listEmbeds();
Sounds good. I left a comment about having to create these, I was wondering if there is the possibility of that changing? It feels a bit odd to have to create a fetcher and a provider just to get a list of them all

2023-09-26 17:14 UTC, jonbarrow commented on run-source.ts
> +  });
I tried this originally, as it's what's also used in the TMDB docs, but it doesn't work with my API key. When using my API key, trying to pass it via a header throws `Invalid API key: You must be granted a valid key.`

2023-09-26 17:16 UTC, jonbarrow commented on run-source.ts
Sounds good to me

2023-09-26 17:27 UTC, mrjvs commented on run-source.ts
> +  }).listEmbeds();
the listing is context dependent, thats the main reason why they are under the main provider instance.
for example if theres a source that doesnt have the NO_CORS flag on it. and you try to list the sources with target set to browser, it wouldn't list that source, it would only list the ones that are available for the browser target.

a side-effect of that system is having to provide a fetcher just to list. but im seeing this problem as more of a niche edgecase rather than a fault in the design. So currently im not thinking of changing that, however I could be convinced otherwise if theres a good realworld case.

2023-09-26 17:27 UTC, mrjvs commented on run-source.ts
> +  });
after testing with some fresh api keys from tmdb. turns out that read only keys are only valid as a header. and read-write keys are only valid as query param. *what a nice api*.

I see two options.
1. detect which key is used, should be simple as read only key always starts with `ey` (its a JWT). this also wouldnt interfere with the other key, as it only uses hex notation, its not possible for it to have a "y".
2. just make it explicit which key you need, somewhere in error messages or in the help message.

I dont mind either, so you can choose

2023-09-26 17:36 UTC, jonbarrow commented on run-source.ts
> +  }).listEmbeds();
The realword use case is this one. When you need to get a full list of all providers metadata but don't care about anything else. I see where this filtering would be useful when you actually plan to run the providers, but not when you just want metadata

I'm not suggesting a change to the current API, but maybe making functions like `getAllSourceMetaSorted` and `getAllEmbedMetaSorted` accessible to library users would be in order. Currently these are only exported in `src/main/meta.ts` but they aren't made available after being bundled

2023-09-26 17:38 UTC, jonbarrow commented on run-source.ts
> +  });
I'll go with option 1, just so people can use their existing keys and not have to worry about it. We don't do any writing so it doesn't matter all that much

Thanks TMDB, amazing design choice

2023-09-26 17:50 UTC, jonbarrow commented on run-source.ts
Moving the script into `src` now makes eslint throw several errors due to the dependency list

> 'NAME' should be listed in the project's dependencies, not devDependencies. (eslintimport/no-extraneous-dependencies)

These are purely for development use though, I'm not sure they belong outside of `devDependencies`?

2023-09-26 17:53 UTC, mrjvs commented on run-source.ts
you can add a eslint ignore comment on top of the file for that. I agree that should stay dev dependencies.

2023-09-26 18:28 UTC, jonbarrow commented
@mrjvs that should be everything. I had to move some stuff around because ESLint kept complaining about things being defined before usage, so that's why some functions/globals might seem like they're defined in weird places. I made a comment about some of the ones I thought were notably odd so people understood why it's the way it is

2023-09-26 18:28 UTC, jonbarrow commented on tsconfig.json
> -    "lib": ["es2021"],
I cri

2023-09-26 18:37 UTC, jonbarrow commented on run-source.ts
> +  }).listEmbeds();
> Ill admit I have may named it a bit weirdly

I think given the context this is named fine, btw. The issue stems mostly from the lack of documentation, so I had to fumble through the source for examples of "proper usage". I think with better documentation (which I know is planned) this confusion will be cleared up

Alternatively a type alias for `targets.NATIVE` such as `targets.ALL` would also be helpful as that makes it clear without having to refer to documentation and only rely on intellisense

2023-09-26 19:14 UTC, binaryoverload submitted a review, later dismissed

2023-09-26 19:14 UTC, binaryoverload commented on src/dev-cli.ts
> +  if (TMDB_API_KEY!.startsWith('ey')) {
You can use the null coalesce operator on line 44 to fix this lint error about the non-null assertion by defaulting the env to an empty string instead of undefined.

i.e. `?? ""`

2023-09-26 19:14 UTC, binaryoverload commented on src/dev-cli.ts
> +  const source = sources.find(({ id }) => id === answers.source)!;
Add a null check instead of doing the non-null assertion.

2023-09-26 19:14 UTC, binaryoverload commented on src/dev-cli.ts
> +  const providers = makeProviders({
In reference to this conversation: https://github.com/movie-web/providers/pull/6#discussion_r1337571167

JVS and I have discussed and we can see the use case for this, we will look at doing something for it but is not in scope for this PR and will be added later

2023-09-26 19:19 UTC, jonbarrow commented on package.json
> +    "test:dev": "npx ts-node ./src/dev-cli.ts",
No you're right, since it's running from an npm script it will check `node_modules` anyway. This was just bad copy-paste from my terminal

2023-09-26 19:20 UTC, jonbarrow commented on src/dev-cli.ts
> +  if (TMDB_API_KEY!.startsWith('ey')) {
It will never not be defined since we immediately throw if it's missing, but I'll do this anyway since the warning is annoying

2023-09-26 19:24 UTC, jonbarrow commented on src/dev-cli.ts
> +  const source = sources.find(({ id }) => id === answers.source)!;
This will never be null. We know this will always exist since the question previous to this uses `sources` list to populate the available choices, and `answers.source` is the chosen source ID from that list

2023-09-26 19:25 UTC, jonbarrow commented on src/dev-cli.ts
> +  const providers = makeProviders({
Sounds good. Honestly just exporting those 2 functions I mentioned in my reply would be enough. They are used interally in the methods that get called on `providers`, so just making them available from the start would skip that step

2023-09-26 19:35 UTC, jonbarrow commented
I have added `tsconfig-paths` to the `tsconfig`, since it allows for the script to import the `src` directory directly. `tsconfig-paths` is needed to resolve the path aliases

Doing this skips the need to compile the TypeScript before running the script, which should speed up testing even more

2023-09-26 19:55 UTC, mrjvs commented on src/dev-cli.ts
> +  const source = sources.find(({ id }) => id === answers.source)!;
I know its in theory not possible, however lets appease the linting gods and just add a quick `if (!source) throw new Error('source not found')`.

(I dont want to disable the linting rule, its been abused by inexperienced contributors before to just ignore ts errors. and want to avoid eslint ignore comments where possible. having an extra check here or there is the price to pay for that I guess)

2023-09-26 19:59 UTC, mrjvs commented on src/dev-cli.ts
> +  const providers = makeProviders({
those methods you named have odd inputs that would be inconvenient to lib users. so I would prefer to dedicate new set of methods for them to use when work on the feature.

2023-09-26 20:05 UTC, jonbarrow commented on src/dev-cli.ts
> +  const providers = makeProviders({
I didn't find them to be that odd (they seem reasonable once it's clear what the inputs are, which documentation could help), but that could just be me. Whatever you guys end up with I'm sure will be fine :+1:

2023-09-26 20:07 UTC, jonbarrow commented on src/dev-cli.ts
> +  const source = sources.find(({ id }) => id === answers.source)!;
> I dont want to disable the linting rule

I also don't, I find linting to be important (which is why I chose to disable only specific lines for the import issue rather than the whole rule). I just personally don't have much issue with warnings being there if I know the warnings are wrong

I'll add the check for the linting gods :+1:

2023-09-27 13:49 UTC, mrjvs approved these changes
I ran some more tests and everything is working as expected. thanks for the work 😄

2023-09-27 13:50 UTC, merged