Fix remotestream base
movie-web/providers pull request #61
Opened 2024-01-02 18:54 UTC by erynith

This pull request resolves #XXX

 - [x] I have read and agreed to the [code of conduct](https://github.com/movie-web/movie-web/blob/dev/.github/CODE_OF_CONDUCT.md).
 - [x] I have read and complied with the [contributing guidelines](https://github.com/movie-web/movie-web/blob/dev/.github/CONTRIBUTING.md).
 - [ ] What I'm implementing was assigned to me and is an [approved issue](https://github.com/movie-web/movie-web/issues?q=is%3Aopen+is%3Aissue+label%3Aapproved). For reference, please take a look at our [GitHub projects](https://github.com/movie-web/movie-web/projects).
 - [x] I have tested all of my changes.

2024-01-04 22:22 UTC, Ilann0 requested changes

2024-01-04 22:22 UTC, Ilann0 commented on src/providers/sources/remotestream.ts
> +const remotestreamBase = atob('aHR0cHM6Ly9mc2IuOG1ldDNkdGpmcmNxY2hjb25xcGtsd3hzeGIyb2N1bWMuc3RyZWFt');
Just run it, why you keep it like this?

```suggestion
const remotestreamBase = 'https://fsb.8met3dtjfrcqchconqpklwxsxb2ocumc.stream';
```

2024-01-04 22:38 UTC, erynith commented on src/providers/sources/remotestream.ts
> +const remotestreamBase = atob('aHR0cHM6Ly9mc2IuOG1ldDNkdGpmcmNxY2hjb25xcGtsd3hzeGIyb2N1bWMuc3RyZWFt');
nuh uh

2024-01-05 18:37 UTC, mrjvs approved these changes
Decided to just kinda fix remotestream completely instead of just modifying the base

2024-01-05 18:37 UTC, merged