Documentation for provider package
movie-web/providers pull request #7
Opened 2023-09-27 17:15 UTC by mrjvs

This pull request resolves no issues, but it was still planned to do :)

 - [X] I have read and agreed to the [code of conduct](https://github.com/movie-web/movie-web/blob/dev/.github/CODE_OF_CONDUCT.md).
 - [X] I have read and complied with the [contributing guidelines](https://github.com/movie-web/movie-web/blob/dev/.github/CONTRIBUTING.md).
 - [ ] What I'm implementing was assigned to me and is an [approved issue](https://github.com/movie-web/movie-web/issues?q=is%3Aopen+is%3Aissue+label%3Aapproved). For reference, please take a look at our [GitHub projects](https://github.com/movie-web/movie-web/projects).
 - [X] I have tested all of my changes.

changes:
 - fetch in makeDefaultFetcher is now a loose type instead of only node-fetch
 - target ALL was added, which is a type alias for NATIVE
 - added like all documentation

2023-09-27 18:04 UTC, binaryoverload requested changes

2023-09-27 18:04 UTC, binaryoverload commented on .docs/package.json
> +  "name": "docus-starter",
```suggestion
  "name": "providers-docs",
```

2023-09-27 23:24 UTC, jonbarrow commented on src/dev-cli.ts
> +/* eslint-disable import/no-extraneous-dependencies */
Is this the best move? I intentionally only disabled this on lines where we wanted specific imports to be ignored. Ignoring it for the whole file could lead to imports would should be caught being missed

2023-09-28 17:43 UTC, binaryoverload commented on src/dev-cli.ts
> +/* eslint-disable import/no-extraneous-dependencies */
You are right, we'll replace this with a comment that will update the behaviour and not disable it

```js
/* eslint import/no-extraneous-dependencies: ["error", {"devDependencies": true}] */
```

2023-09-28 17:48 UTC, jonbarrow commented on src/dev-cli.ts
> +/* eslint-disable import/no-extraneous-dependencies */
Wow I didn't know eslint comments could do that, neato. Maybe the actual rule itself should be updated then?

2023-09-28 17:49 UTC, binaryoverload commented
> Are you opposed to also implementing JSDoc/TSDoc comments to add some details about the library functions when using intellisense? I'm aware this might be out of scope for this PR, but I felt it was tangentially related to documentation
> 
> I recently spent a lot of time adding TSDoc comments to a different library I've been maintaining (seen below) and they've been quite useful. I'm willing to be the one to put in the leg work there in a different PR but I'd likely be relying on you jvs for any info about the functions I need help understanding ![Screenshot_from_2023-09-10_02-08-57](https://user-images.githubusercontent.com/27011796/271128451-0a910b20-1278-482d-bb6d-88594c0f0943.png)

We've had a chat about this internally and we're not interested in adding TSDoc right now - mainly because it's another thing to maintain and this library is not very complex so the TSDoc comments wouldn't add much to the method and parameter names.

2023-09-28 17:51 UTC, binaryoverload commented on src/dev-cli.ts
> +/* eslint-disable import/no-extraneous-dependencies */
We don't want to do that because we don't want to allow dev dependencies to be used in the rest of the project. This file is whitelisted as it is only a dev file and won't be packaged.

2023-09-28 17:53 UTC, binaryoverload approved these changes

2023-09-28 17:53 UTC, merged